#!/bin/bash
set -o nounset -o pipefail
trap 'exit 3' ERR

(exec 1>&2
date
cat <<EOF
BH_USER=${BH_USER}
BH_REPO=${BH_REPO}
BH_COMMIT=${BH_COMMIT}
BH_UUID=${BH_UUID}
EOF
)

sleep 5

cat <<"EOF"
<!DOCTYPE html>
<html lang=en>
<title>a title</title>
<p>a paragraph
EOF

exit 0
